### ISSUE TITLE
Error launching on msxpy: missing nondos.rom

### ISSUE THREAD

**Issue by matheusjgsantos** [flok99/pymsx#1]
Got this error while launching the python program:

$ python3 ./msx.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Loading SCC rom nondos.rom...
Traceback (most recent call last):
  File "./msx.py", line 35, in <module>
    scc_obj = scc(scc_rom_file, debug) if scc_rom_file else None
  File "/Users/xxxxxxxxx/Documents/Personal/Projects/msx/pymsx/scc.py", line 11, in __init__
    fh = open(scc_rom_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'nondos.rom'

Couldn't find the file nondos.rom anywhere. Any way to bypass the SCC rom or any other file that we can use to replace this one?

**Comment by matheusjgsantos** [comment]
Got it:
#scc_obj = scc(scc_rom_file, debug) if scc_rom_file else None
#scc_sig = scc_obj.get_signature() if scc_obj else None
